apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: wanderlust   # Replace 'your-namespace-name' with your desired namespace
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
