apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  namespace: wanderlust  # Ensure this matches the namespace in your Deployment
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: kumarsumit74604/frontend-wanderlust:latest
    ports:
    - containerPort: 5173
